# This rule is not used by the project controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to agent.ai.solo.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: autogenteam-viewer-role
rules:
- apiGroups:
  - agent.ai.solo.io
  resources:
  - autogenteams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agent.ai.solo.io
  resources:
  - autogenteams/status
  verbs:
  - get
