apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kagent.fullname" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kagent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kagent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "kagent.fullname" . }}
      containers:
        - name: controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.controller.image.registry }}/{{ .Values.controller.image.repository }}:{{ coalesce .Values.global.tag .Values.controller.image.tag .Chart.Version }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          env:
            - name: KAGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
        - name: app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.registry }}/{{ .Values.app.image.repository }}:{{ coalesce .Values.global.tag .Values.app.image.tag .Chart.Version }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openai.secretName }}
                  key: {{ .Values.openai.secretKey }}
            - name: OTEL_TRACING_ENABLED
              value: {{ .Values.otel.tracing.enabled | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.otel.tracing.exporter.otlp.endpoint | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_TIMEOUT
              value: {{ .Values.otel.tracing.exporter.otlp.timeout | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
              value: {{ .Values.otel.tracing.exporter.otlp.insecure | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.app.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/version
              port: {{ .Values.service.ports.app.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 3
        - name: ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.registry }}/{{ .Values.ui.image.repository }}:{{ coalesce .Values.global.tag .Values.ui.image.tag .Chart.Version }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://{{ include "kagent.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local/api"
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.ui.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
