apiVersion: v1
kind: Service
metadata:
  name: {{ include "kagent.fullname" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.ui.port }}
      targetPort: {{ .Values.service.ports.ui.targetPort }}
      protocol: TCP
      name: ui
    - port: {{ .Values.service.ports.app.port }}
      targetPort: {{ .Values.service.ports.app.targetPort }}
      protocol: TCP
      name: app
    - port: {{ .Values.service.ports.a2a.port }}
      targetPort: {{ .Values.service.ports.a2a.targetPort }}
      protocol: TCP
      name: a2a
  selector:
    {{- include "kagent.selectorLabels" . | nindent 4 }}