# Default values for kagent
replicaCount: 1

global:
  tag: ""

openai:
  enabled: true
  secretName: "kagent-openai"
  apiKey: ""
  secretKey: "OPENAI_API_KEY"

controller:
  image:
    registry: ghcr.io
    repository: kagent-dev/kagent/controller
    tag: ""  # Will default to global, then Chart version
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

app:
  image:
    registry: ghcr.io
    repository: kagent-dev/kagent/app
    tag: ""  # Will default to global, then Chart version
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

ui:
  image:
    registry: ghcr.io
    repository: kagent-dev/kagent/ui
    tag: ""  # Will default to global, then Chart version
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  

service:
  type: ClusterIP
  ports:
    ui:
      port: 80
      targetPort: 80
    app:
      port: 8081
      targetPort: 8081

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

contrib:
  agents:
    k8s:
      enabled: true
      modelConfigRef: default-model-config
    istio:
      enabled: true
      modelConfigRef: default-model-config
    helm:
      enabled: true
      modelConfigRef: default-model-config
    promql:
      enabled: true
      modelConfigRef: default-model-config
    observability:
      prometheus:
        url: ""
        username: ""
        password: ""
      grafana:
        url: ""
        username: ""
        password: ""
        apiKey: ""
      enabled: true
      modelConfigRef: default-model-config
    argoRolloutsConversion:
      enabled: true
      modelConfigRef: default-model-config

otel:
  tracing:
    enabled: false
    exporter:
      otlp:
        endpoint: http://localhost:4317
        timeout: 10
        insecure: true
